services:
  backend:
    image: ghcr.io/medblocks/erpnext/worker
    command:
      - /home/frappe/frappe-bench/env/bin/gunicorn
      - --bind=0.0.0.0:8000
      - --config=/opt/patches/gevent_patch.py
      - --log-file=-
      - --preload
      - --threads=4
      - --timeout=120
      - --worker-class=gevent
      - --worker-tmp-dir=/dev/shm
      - --workers=2
      - frappe.app:application
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      REDIS_CACHE: ${REDIS_CACHE}
      REDIS_QUEUE: ${REDIS_QUEUE}
      REDIS_SOCKETIO: ${REDIS_SOCKETIO}
      SOCKETIO_PORT: 9000
    volumes:
      - ./frappe.log:/home/frappe/frappe-bench/sites/mb.biograph.care/logs/frappe.log
      - ./overrides/common_site_config.json:/home/frappe/frappe-bench/sites/common_site_config.json
      - ./overrides/site_config.json:/home/frappe/frappe-bench/sites/mb.biograph.care/site_config.json
    ports:
      - 8000:8000

  frontend:
    restart: on-failure
    image: ghcr.io/medblocks/erpnext/nginx
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:9000
      FRAPPE_SITE_NAME_HEADER: mb.biograph.care
      UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
      UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
      UPSTREAM_REAL_IP_RECURSIVE: ${UPSTREAM_REAL_IP_RECURSIVE:-off}
    depends_on:
      - backend
      - websocket
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
    ports:
      - 8080:8080

  websocket:
    image: ghcr.io/medblocks/erpnext/socketio
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:9000
      FRAPPE_SITE_NAME_HEADER: localhost
      UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
      UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
      UPSTREAM_REAL_IP_RECURSIVE: ${UPSTREAM_REAL_IP_RECURSIVE:-off}
  queue-short:
    image: ghcr.io/medblocks/erpnext/worker
    command: bench worker --queue short
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      REDIS_CACHE: ${REDIS_CACHE}
      REDIS_QUEUE: ${REDIS_QUEUE}
      REDIS_SOCKETIO: ${REDIS_SOCKETIO}
      SOCKETIO_PORT: 9000

  queue-default:
    image: ghcr.io/medblocks/erpnext/worker
    command: bench worker --queue default
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      REDIS_CACHE: ${REDIS_CACHE}
      REDIS_QUEUE: ${REDIS_QUEUE}
      REDIS_SOCKETIO: ${REDIS_SOCKETIO}
      SOCKETIO_PORT: 9000

  queue-long:
    image: ghcr.io/medblocks/erpnext/worker
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      REDIS_CACHE: ${REDIS_CACHE}
      REDIS_QUEUE: ${REDIS_QUEUE}
      REDIS_SOCKETIO: ${REDIS_SOCKETIO}
      SOCKETIO_PORT: 9000
    command: bench worker --queue long

  scheduler:
    image: ghcr.io/medblocks/erpnext/worker
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      REDIS_CACHE: ${REDIS_CACHE}
      REDIS_QUEUE: ${REDIS_QUEUE}
      REDIS_SOCKETIO: ${REDIS_SOCKETIO}
      SOCKETIO_PORT: 9000
    command: bench schedule

  mariadb:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      # MARIADB_DATABASE: erpnext_db
      # MARIADB_USER: erpnext_user
      # MARIADB_PASSWORD: erpnext_password
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql

  migrate:
    restart: on-failure
    image: ghcr.io/medblocks/erpnext/worker
    command: bench --site mb.biograph.care  override-migrate
    volumes:
      - ./repos/tacten_core/tacten_core/s3_update.py:/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/s3_backup_settings/s3_backup_settings.py
      - ./overrides/common_site_config.json:/home/frappe/frappe-bench/sites/common_site_config.json
      - ./overrides/site_config.json:/home/frappe/frappe-bench/sites/mb.biograph.care/site_config.json

  redis-cache:
    image: redis:alpine

  redis-queue:
    image: redis:alpine

  redis-socketio:
    image: redis:alpine

volumes:
  mariadb-data:


