services:
  backend:
    image: ghcr.io/medblocks/erpnext/worker
    command:
      - /home/frappe/frappe-bench/env/bin/gunicorn
      - --bind=0.0.0.0:8000
      - --config=/opt/patches/gevent_patch.py
      - --log-file=-
      - --preload
      - --threads=4
      - --timeout=120
      - --worker-class=gevent
      - --worker-tmp-dir=/dev/shm
      - --workers=2
      - frappe.app:application
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      REDIS_CACHE: ${REDIS_CACHE}
      REDIS_QUEUE: ${REDIS_QUEUE}
      REDIS_SOCKETIO: ${REDIS_SOCKETIO}
      SOCKETIO_PORT: 9000
    depends_on:
      - queue-short
      - queue-default
      - queue-long
      - scheduler
      - redis-cache
      - redis-socketio
    volumes:
      - ./frappe.log:/home/frappe/frappe-bench/sites/mb.biograph.care/logs/frappe.log
      - ./overrides/common_site_config.json:/home/frappe/frappe-bench/sites/common_site_config.json
      - ./overrides/site_config.json:/home/frappe/frappe-bench/sites/mb.biograph.care/site_config.json
      # - ./private:/home/frappe/frappe-bench/sites/mb.biograph.care/private/files
      # - ./public:/home/frappe/frappe-bench/sites/mb.biograph.care/public/files
    ports:
      - 8000:8000


  frontend:
    restart: on-failure
    image: ghcr.io/medblocks/erpnext/nginx
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:9000
      FRAPPE_SITE_NAME_HEADER: mb.biograph.care
      UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
      UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
      UPSTREAM_REAL_IP_RECURSIVE: ${UPSTREAM_REAL_IP_RECURSIVE:-off}
    depends_on:
      - backend
      - websocket
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
    ports:
      - 8080:8080

  websocket:
    image: ghcr.io/medblocks/erpnext/socketio
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:9000
      FRAPPE_SITE_NAME_HEADER: localhost
      UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
      UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
      UPSTREAM_REAL_IP_RECURSIVE: ${UPSTREAM_REAL_IP_RECURSIVE:-off}
    depends_on:
      - backend
      - redis-socketio

  queue-short:
    image: ghcr.io/medblocks/erpnext/worker
    command: bench worker --queue short
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      REDIS_CACHE: ${REDIS_CACHE}
      REDIS_QUEUE: ${REDIS_QUEUE}
      REDIS_SOCKETIO: ${REDIS_SOCKETIO}
      SOCKETIO_PORT: 9000
    volumes:
      - ./overrides/site_config.json:/home/frappe/frappe-bench/sites/mb.biograph.care/site_config.json
    depends_on:
      - redis-queue

  queue-default:
    image: ghcr.io/medblocks/erpnext/worker
    command: bench worker --queue default
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      REDIS_CACHE: ${REDIS_CACHE}
      REDIS_QUEUE: ${REDIS_QUEUE}
      REDIS_SOCKETIO: ${REDIS_SOCKETIO}
      SOCKETIO_PORT: 9000
    depends_on:
      - redis-queue
    volumes:
      - ./overrides/site_config.json:/home/frappe/frappe-bench/sites/mb.biograph.care/site_config.json
  queue-long:
    image: ghcr.io/medblocks/erpnext/worker
    command: bench worker --queue long
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      REDIS_CACHE: ${REDIS_CACHE}
      REDIS_QUEUE: ${REDIS_QUEUE}
      REDIS_SOCKETIO: ${REDIS_SOCKETIO}
      SOCKETIO_PORT: 9000
    depends_on:
      - redis-queue
    volumes:
      - ./overrides/site_config.json:/home/frappe/frappe-bench/sites/mb.biograph.care/site_config.json

  scheduler:
    image: ghcr.io/medblocks/erpnext/worker
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      REDIS_CACHE: ${REDIS_CACHE}
      REDIS_QUEUE: ${REDIS_QUEUE}
      REDIS_SOCKETIO: ${REDIS_SOCKETIO}
      SOCKETIO_PORT: 9000
    command: bench schedule
    volumes:
      - ./overrides/site_config.json:/home/frappe/frappe-bench/sites/mb.biograph.care/site_config.json

  mariadb:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      # MARIADB_DATABASE: erpnext_db
      # MARIADB_USER: erpnext_user
      # MARIADB_PASSWORD: erpnext_password
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql
    depends_on:
      - redis-queue
  migrate:
    restart: on-failure
    image: ghcr.io/medblocks/erpnext/worker
    command: bench --site mb.biograph.care migrate
    volumes:
      - ./overrides/common_site_config.json:/home/frappe/frappe-bench/sites/common_site_config.json
      - ./overrides/site_config.json:/home/frappe/frappe-bench/sites/mb.biograph.care/site_config.json
    environment:
      - ADMIN_PASSWORD=Medblocks@123

  install-app:
    restart: on-failure
    image: ghcr.io/medblocks/erpnext/worker
    command: bench --site mb.biograph.care setup-site
    volumes:
      # - ./sites/apps.txt:/home/frappe/frappe-bench/sites/apps.txt
      # - ./repos/tacten_core/tacten_core:/home/frappe/frappe-bench/apps/tacten_core/tacten_core
      - ./overrides/common_site_config.json:/home/frappe/frappe-bench/sites/common_site_config.json
      - ./overrides/site_config.json:/home/frappe/frappe-bench/sites/mb.biograph.care/site_config.json
    environment:
      - ADMIN_PASSWORD=Medblocks@123 

  remove-app: 
    restart: on-failure
    image: ghcr.io/medblocks/erpnext/worker
    command: bench --site mb.biograph.care uninstall-app ${APPS}
    volumes:
      # - ./sites/apps.txt:/home/frappe/frappe-bench/sites/apps.txt
      # - ./repos/tacten_core/tacten_core:/home/frappe/frappe-bench/apps/tacten_core/tacten_core
      - ./overrides/common_site_config.json:/home/frappe/frappe-bench/sites/common_site_config.json
      - ./overrides/site_config.json:/home/frappe/frappe-bench/sites/mb.biograph.care/site_config.json

  new-app:
    restart: on-failure
    image: ghcr.io/medblocks/erpnext/worker
    command: bench --site mb.biograph.care install-app ${APPS}
    volumes:
      # - ./sites/apps.txt:/home/frappe/frappe-bench/sites/apps.txt
      # - ./repos/tacten_core/tacten_core:/home/frappe/frappe-bench/apps/tacten_core/tacten_core
      - ./overrides/common_site_config.json:/home/frappe/frappe-bench/sites/common_site_config.json
      - ./overrides/site_config.json:/home/frappe/frappe-bench/sites/mb.biograph.care/site_config.json
  # get-app:
  #   restart: on-failure
  #   image: ghcr.io/medblocks/erpnext/worker
  #   command: bench get-app ${APPS}
  #   volumes:
  #     # - ./sites/apps.txt:/home/frappe/frappe-bench/sites/apps.txt
  #     # - ./repos/tacten_core/tacten_core:/home/frappe/frappe-bench/apps/tacten_core/tacten_core
  #     - ./overrides/common_site_config.json:/home/frappe/frappe-bench/sites/common_site_config.json
  #     - ./overrides/site_config.json:/home/frappe/frappe-bench/sites/mb.biograph.care/site_config.json  

  redis-cache:
    image: redis:alpine

  redis-queue:
    image: redis:alpine

  redis-socketio:
    image: redis:alpine

volumes:
  mariadb-data:


