services:
  reinstall:
    restart: on-failure
    image: ${WORKER_IMAGE}
    command: bench --site erpnext.localhost reinstall --yes --mariadb-root-username root --mariadb-root-password MariaDBPassword@123 --admin-password AdminPassword@123