services:
  reinstall:
    restart: on-failure
    image: ghcr.io/tacten/erpnext-template/worker:main
    command: bench --site erpnext.localhost reinstall --yes --mariadb-root-username root --mariadb-root-password MariaDBPassword@123 --admin-password AdminPassword@123