services:
  backend:
    user: "0:0"
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites

  frontend:
    # environment:
    #     FRAPPE_SITE_NAME_HEADER: ${SITE}
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template

  queue-short:
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites

  queue-default:
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites

  queue-long:
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites

  scheduler:
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites
  
  migrate:
    restart: on-failure
    image: ${WORKER_IMAGE}
    user: "0:0"
    command: bash -c "bench set-config -g developer_mode 1 && bench --site ${SITE} migrate"
    environment:
    - ADMIN_PASSWORD=AdminPassword@123
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites
